services:
  caddy:
    image: local/caddy:latest
    restart: unless-stopped
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ~/Documents/homelab-data/caddy/config:/config
      - ~/Documents/homelab-data/caddy/certs:/certs
      - ~/Documents/homelab-data/caddy/data:/data
    env_file:
      - .env
