version: "3.8"

services:
  caddy:
    image: local/caddy:latest
    restart: unless-stopped
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs
      - ./config:/config
      - ./data:/data
      - ./sites:/srv
    env_file:
      - .env
