services:
  caddy:
    build: .
    restart: unless-stopped
    container_name: caddy
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_certs:/certs
      - caddy_data:/data
    env_file:
      - .env

volumes:
  caddy_config:
    name: caddy_config
  caddy_certs:
    name: caddy_certs
  caddy_data:
    name: caddy_data
