services:
  bind9:
    image: ubuntu/bind9:latest
    restart: unless-stopped
    container_name: bind9
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - BIND9_USER=root
      - TZ=Pacific/Auckland
    volumes:
      - ./bind:/etc/bind
      - bind9_cache:/var/cache/bind
      - bind9_records:/var/lib/bind

volumes:
  bind9_cache:
    name: bind9_cache
  bind9_records:
    name: bind9_records
