version: '3'

services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.30.3-alpine
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "4000:80"
    environment:
      - DOMAIN=https://vaultwarden.boole.site
    volumes:
      - ./data:/data
