services:
  bind9:
    image: ubuntu/bind9:latest
    restart: unless-stopped
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=UTC
    volumes:
      - ./config:/etc/bind:ro
      - bind9_cache:/var/cache/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"

volumes:
  bind9_cache:
