services:
  syncthing:
    image: linuxserver/syncthing:1.27.6
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - syncthing_config:/config
      - syncthing_data1:/data1
      - syncthing_data2:/data2

    ports:
      - 4250:8384 # GUI
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp # Protocol discovery
    restart: unless-stopped

volumes:
  syncthing_config:
    name: syncthing_config
  syncthing_data1:
    name: syncthing_data1
  syncthing_data2:
    name: syncthing_data2
