services:
  kuma:
    image: louislam/uptime-kuma:1.23.13-alpine
    restart: unless-stopped
    container_name: kuma
    ports:
      - 4150:3001
    volumes:
      - kuma_data:/app/data

volumes:
  kuma_data:
    name: kuma_data
